[[plugins]]
plugin_chinese_name = "快速命令"
plugin_path = "/mnt/sharedisk/码上寄/python/MyDeskPetCore/src/Plugin/QuickStart"
plugin_name = "QuickStart"
plugin_type = "menu"
enabled = false

[window]
x = 300
y = 200
width = 400
height = 400

[model]
model_path = "resources/Live2dModel/Firefly-desktop/Firefly.model3.json"
scale = 0.75

[animation]
frame_rate_ms = 60
