[[plugins]]
plugin_chinese_name = "快速命令"
plugin_path = "src/Plugin/QuickStart"
plugin_name = "QuickStart"
plugin_type = "menu"
enabled = true

[[plugins]]
plugin_chinese_name = "鼠标跟随"
plugin_path = "src/Plugin/FollowMouse"
plugin_name = "FollowMouse"
plugin_type = "lasting"
enabled = true

[[plugins]]
icon = ""
plugin_chinese_name = " 沉浸式桌宠"
plugin_name = "Immersive"
function_name = "immersive"
plugin_type = "init"
plugin_path = "src/Plugin/Immersive"
enabled = true

[[plugins]]
icon = ""
plugin_chinese_name = " 沉浸式桌宠增强"
plugin_name = "ImmersivePlus"
function_name = "immersive_plus"
plugin_type = "init"
plugin_path = "src/Plugin/ImmersivePlus"
enabled = true

[[plugins]]
icon = "src/Plugin/CountdownTimer/倒计时.svg"
plugin_chinese_name = "倒计时"
plugin_name = "CountdownTimer"
plugin_type = "menu"
plugin_path = "src/Plugin/CountdownTimer"
enabled = true

[[plugins]]
icon = ""
plugin_chinese_name = "表情选择"
plugin_name = "EmojiSelection"
plugin_type = "menu"
plugin_path = "src/Plugin/EmojiSelection"
enabled = true

[[plugins]]
icon = ""
plugin_chinese_name = "动作选择"
plugin_name = "ActionSelect"
plugin_type = "menu"
plugin_path = "src/Plugin/ActionSelect"
enabled = true

[[plugins]]
icon = "VIEW"
plugin_chinese_name = "显示控制"
plugin_name = "VisibilityToggle"
plugin_type = "menu"
plugin_path = "src/Plugin/VisibilityToggle"
enabled = true

[window]
x = 300
y = 300
width = 500
height = 500
background_color = [
    1,
    2,
    3,
    0,
]

[model]
model_path = "resources/Live2dModel/Firefly-desktop/Firefly.model3.json"
scale = 0.75

[animation]
frame_rate_ms = 60
