[[plugins]]
plugin_chinese_name = "快速命令"
plugin_path = "src/Plugin/QuickStart"
plugin_name = "QuickStart"
plugin_type = "menu"
enabled = true

[[plugins]]
plugin_chinese_name = "鼠标跟随"
plugin_path = "src/Plugin/FollowMouse"
plugin_name = "FollowMouse"
plugin_type = "lasting"
enabled = true

[window]
x = 300
y = 200
width = 400
height = 400

[model]
model_path = "resources/Live2dModel/Firefly-desktop/Firefly.model3.json"
scale = 0.75

[animation]
frame_rate_ms = 60
